### ISSUE TITLE
Audio output selection not working

### ISSUE THREAD

**Issue by Lagby** [Firebottle/Firebot#433]
#### Describe your issue or feature request (details are helpful!):
I installed recent beta this morning.  Everything was working.

Changed sound source, noticed it wasn't actually using the said sound source. Restarted firebot, clicked a button on the sound board and this happened.

https://i.gyazo.com/a03c10368c00a233dd3e54a81881dccb.png

Seems all the sound buttons have lost action
https://i.gyazo.com/09ec224bbe2af84f29a103e298968862.png

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?
4.5.0. beta 1

- What are the steps to reproduce the issue?
1) changed Sound Output device
2) clicked sound button
3) rewards followed

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.
[lagby.zip](https://github.com/Firebottle/Firebot/files/1513729/lagby.zip)

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by ebiggz** [comment]
Yikes, thats not good. Thanks for the heads up. While I couldnt reproduce the issue exactly, I did find and fix several of issues with manually triggering buttons, and various other issues with board data management. These fixes are in the new beta that just went out. Hopefully the issue is resolved, but I am going to leave this open for awhile until we can be more sure.

**Comment by Lagby** [comment]
Tested with a reinstall and restore of 4.4.5 and installed beta 2. 
had to re select sound file for first sound button and all buttons worked after fixing the first button.

Also, Settings: Sound output isn't working.  Continues to remain on default system sounds.

**Comment by ebiggz** [comment]
Hmm. I don't see the same issue with sound output on my end. I am able to successfully change sound output currently. We may have to troubleshoot a bit to nail down what exactly is different on your end that's causing it to fail for you.

The new audio feature allows you to change the audio output device globally for Firebot in the settings tab as you mentioned, but you can also customize the output device per sound effect.

For a button that isn't playing sound to the right place, click **Edit** and open up the Play Sound effect. What is the "Audio Output Device" option set to?

**Comment by Lagby** [comment]
Tested with individual buttons sound along with settings pointing to (cable
a). Still continues to output to default system sound.

Even after restarting the program.

**Comment by Firebottle** [comment]
Just out of curiosity, have you tried running Firebot as admin?

**Comment by Lagby** [comment]
I did. No change.

**Comment by ebiggz** [comment]
Would you be able to attach a screenshot of the list of output devices you have? (If its easier PM it to one of us on discord)

**Comment by Lagby** [comment]
https://i.gyazo.com/ed5eb007c1866765f3d013a22378c5b8.png

**Comment by Firebottle** [comment]
I have virtual cables (though not the VB Audio Cables) on both machines at my place. I can run some tests to see if I can reproduce the issue.

When testing I was running the audio directly into voicemeeter vaio and vaio aux. Both of those seemed to work for me. So it might be some sort of issue with virtual cables.

Could you try setting it to "Voicemeeter Input (VoiceMeeter VAIO)" just to see if it gives you anything?

**Comment by Lagby** [comment]
Tested with Voicemeeter Input (VoiceMeeter VAIO) and Aux.  Both actually function properly.

But selecting the VB audio Cables it does not function.  It reverts back to system default sounds (output sound, not selection)

**Comment by ThePerry-2015** [comment]
I just tested this with VB-Audio Virtual Cable (1.0.3.5) and I can move the sounds from default(Desktop Speakers (VAIO)) and to VB Audio Cable Output. With my current setup the sound ends up played over the desktop speakers as I've set the output channel for the Virtual Cable in Voicemeeter to A1 which is the default speakers. But I can easily switch that to my headset (VAIO AUX) or as a mic in Discord. I use the meters as indicators that it works, and I've seen it on your stream that the indicators didn't react at all when you changed it around. So I'm not sure what's making it not work on your setup.
I'll try to attach an animated GIF here, hopefully it works just to show how it reacts on my end.
![2017-12-06_22-59-30](https://user-images.githubusercontent.com/25306770/33687907-f9175d44-dad9-11e7-83ee-1a362e42ecab.gif)

**Comment by Lagby** [comment]
That is odd.  Mine will not select anything outside of VM virtual cables..

**Comment by ThePerry-2015** [comment]
Which output "type" have you chosen for your Virtual Cable in Voicemeeter?
WDM, KS or MME?
![2017-12-06_23-18-48](https://user-images.githubusercontent.com/25306770/33688548-0ea25c48-dadc-11e7-830e-38cd5abeb9db.png)

**Comment by Lagby** [comment]
WDM on all of them.

**Comment by Firebottle** [comment]
Is this still an issue?
